-- Geração de Modelo físico
-- SQL ANSI 2003 - Ajustado manualmente

CREATE TABLE MECANICO (
    ID_MECANICO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_MECANICO VARCHAR(100),
    ESPECIALIDADE VARCHAR(100),
    TELEFONE VARCHAR(20),
    STATUS ENUM('inativo','ativo')
);

CREATE TABLE SERVICO (
    ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_SERVICO VARCHAR(50),
    DESCRICAO VARCHAR(100),
    VALOR_SERVICO DECIMAL(10,2)
);

CREATE TABLE PECA (
    ID_PECA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PECA VARCHAR(100),
    CODIGO VARCHAR(30),
    FABRICANTE VARCHAR(50),
    QUANTIDADE_ESTOQUE INT,
    PRECO_UNITARIO DECIMAL(10,2)
);

CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100),
    TELEFONE_CLIENTE VARCHAR(20),
    DOCUMENTO VARCHAR(30),
    ENDERECO_CLIENTE VARCHAR(150)
);

CREATE TABLE VEICULO (
    ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
    PLACA VARCHAR(10),
    MODELO VARCHAR(30),
    MARCA VARCHAR(50),
    ANO INT,
    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE OS (
    ID_OS INT AUTO_INCREMENT PRIMARY KEY,
    DATA_ABERTURA DATE,
    DATA_FECHAMENTO DATE,
    STATUS_OS ENUM('aberta', 'em_execucao', 'finalizada', 'cancelada'),
    ID_VEICULO INT,
    FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(ID_VEICULO)
);

CREATE TABLE OS_PECA (
    ID_OS INT,
    ID_PECA INT,
    QUANTIDADE INT,
    VALOR_UNITARIO DECIMAL(10,2),
    VALOR_TOTAL DECIMAL(10,2),
    PRIMARY KEY (ID_OS, ID_PECA),
    FOREIGN KEY (ID_OS) REFERENCES OS(ID_OS),
    FOREIGN KEY (ID_PECA) REFERENCES PECA(ID_PECA)
);

CREATE TABLE OS_MECANICO (
    ID_OS INT,
    ID_MECANICO INT,
    FUNCAO VARCHAR(100),
    PRIMARY KEY (ID_OS, ID_MECANICO),
    FOREIGN KEY (ID_OS) REFERENCES OS(ID_OS),
    FOREIGN KEY (ID_MECANICO) REFERENCES MECANICO(ID_MECANICO)
);

CREATE TABLE OS_SERVICO (
    ID_OS INT,
    ID_SERVICO INT,
    QUANTIDADE_SERVICOS INT,
    HORAS TIME,
    VALOR DECIMAL(10,2),
    PRIMARY KEY (ID_OS, ID_SERVICO),
    FOREIGN KEY (ID_OS) REFERENCES OS(ID_OS),
    FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO(ID_SERVICO)
);
